### ISSUE TITLE
Not work for me on edge

### ISSUE THREAD

**Issue by abdelkaderG** [matthias-schuetz/angular2-seed#5]
Gives this error : 
HTML1300: Une navigation s’est produite.
Fichier : localhost:8080
Error: TypeError: L’objet ne gère pas la propriété ou la méthode « keys »
	   at Anonymous function (eval code:32249:9)
	   at Anonymous function (eval code:32248:5)
	   at linkDynamicModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3252:5)
	   at getModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3220:9)
	   at Anonymous function (http://localhost:8080/src/vendor/node_modules/system.src.js:3256:9)
	   at Anonymous function (eval code:32634:5)
	   at linkDynamicModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3252:5)
	   at getModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3220:9)
	   at Anonymous function (http://localhost:8080/src/vendor/node_modules/system.src.js:3256:9)
	   at Anonymous function (eval code:32797:5)
	Error loading http://localhost:8080/src/bootstrap.js
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "Error"
      },
      description: "TypeError: L’objet ne gère pas la propriété ou la méthode « keys »
	   at Anonymous function (eval code:32249:9)
	   at Anonymous function (eval code:32248:5)
	   at linkDynamicModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3252:5)
	   at getModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3220:9)
	   at Anonymous function (http://localhost:8080/src/vendor/node_modules/system.src.js:3256:9)
	   at Anonymous function (eval code:32634:5)
	   at linkDynamicModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3252:5)
	   at getModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3220:9)
	   at Anonymous function (http://localhost:8080/src/vendor/node_modules/system.src.js:3256:9)
	   at Anonymous function (eval code:32797:5)
	Error loading http://localhost:8080/src/bootstrap.js",
      message: "TypeError: L’objet ne gère pas la propriété ou la méthode « keys »
	   at Anonymous function (eval code:32249:9)
	   at Anonymous function (eval code:32248:5)
	   at linkDynamicModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3252:5)
	   at getModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3220:9)
	   at Anonymous function (http://localhost:8080/src/vendor/node_modules/system.src.js:3256:9)
	   at Anonymous function (eval code:32634:5)
	   at linkDynamicModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3252:5)
	   at getModule (http://localhost:8080/src/vendor/node_modules/system.src.js:3220:9)
	   at Anonymous function (http://localhost:8080/src/vendor/node_modules/system.src.js:3256:9)
	   at Anonymous function (eval code:32797:5)
	Error loading http://localhost:8080/src/bootstrap.js",
      name: "Error",
      originalErr: { },
      stack: null
   }

**Comment by matthias-schuetz** [comment]
I can't reproduce the issue, maybe it's a node_modules problem since I switched from es6-shims to core-js. Please try deleting your node_modules folder and do a `npm install` again. The seed should work fine in Edge.
