### ISSUE TITLE
SyntaxError...

### ISSUE THREAD

**Issue by joachim-bl** [matthias-schuetz/angular2-seed#9]
Hi,
I have "npm i" the project and then "gulp build:prod" and got this error:
 
[10:24:19] Starting 'prod:compile:aot'...
{ Error: Command failed: npm run aot || npm run aot-win && npm run aot-rollup || npm run aot-rollup-win
C:\Develop\angular\minimal-seed\angular2-seed-master\node_modules\.bin\ngc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

can u help?

**Comment by matthias-schuetz** [comment]
Not directly, what operating system are you using?

**Comment by jmeinlschmidt** [comment]
I've had the same problem.

Try switching to the lastest stable version of Node (using `NVM` or `n`).
Delete the whole node_modules directory `rm -r node_modules`
Clean npm cache `npm clean cache`
Install all dependencies `npm install`
`gulp build:prod`
